linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - unused
  # TODO: Re-enable these linters after fixing code issues:
  # - staticcheck: 30+ deprecation warnings (io/ioutil, grpc.DialContext, etc)
  # - errcheck: 20+ unchecked error returns (os.Remove, Close, Setenv, Unsetenv)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
