linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
  # TODO: Re-enable staticcheck after fixing deprecation warnings
  # staticcheck currently reports 30+ issues including:
  # - io/ioutil deprecations (use io/os instead)
  # - grpc.DialContext deprecation (use NewClient)
  # - Empty branches (SA9003)
  # - Identical expressions (SA4000)
  # - Unused variables (SA4006)
  # - Deprecated lipgloss methods (SA1019)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
