linters:
  disable:
    - errcheck
    - unused
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign

linters-settings:
  govet:
    check-shadowing: true
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - dev-workspace
