// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_agents.sql

package queries

import (
	"context"
	"database/sql"
)

const addChildAgent = `-- name: AddChildAgent :one
INSERT INTO agent_agents (parent_agent_id, child_agent_id)
VALUES (?, ?)
RETURNING id, parent_agent_id, child_agent_id, created_at
`

type AddChildAgentParams struct {
	ParentAgentID int64 `json:"parent_agent_id"`
	ChildAgentID  int64 `json:"child_agent_id"`
}

func (q *Queries) AddChildAgent(ctx context.Context, arg AddChildAgentParams) (AgentAgent, error) {
	row := q.db.QueryRowContext(ctx, addChildAgent, arg.ParentAgentID, arg.ChildAgentID)
	var i AgentAgent
	err := row.Scan(
		&i.ID,
		&i.ParentAgentID,
		&i.ChildAgentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllChildAgentsForAgent = `-- name: DeleteAllChildAgentsForAgent :exec
DELETE FROM agent_agents WHERE parent_agent_id = ?
`

func (q *Queries) DeleteAllChildAgentsForAgent(ctx context.Context, parentAgentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllChildAgentsForAgent, parentAgentID)
	return err
}

const getChildAgentRelationship = `-- name: GetChildAgentRelationship :one
SELECT id, parent_agent_id, child_agent_id, created_at FROM agent_agents
WHERE parent_agent_id = ? AND child_agent_id = ?
`

type GetChildAgentRelationshipParams struct {
	ParentAgentID int64 `json:"parent_agent_id"`
	ChildAgentID  int64 `json:"child_agent_id"`
}

func (q *Queries) GetChildAgentRelationship(ctx context.Context, arg GetChildAgentRelationshipParams) (AgentAgent, error) {
	row := q.db.QueryRowContext(ctx, getChildAgentRelationship, arg.ParentAgentID, arg.ChildAgentID)
	var i AgentAgent
	err := row.Scan(
		&i.ID,
		&i.ParentAgentID,
		&i.ChildAgentID,
		&i.CreatedAt,
	)
	return i, err
}

const listChildAgents = `-- name: ListChildAgents :many
SELECT aa.id, aa.parent_agent_id, aa.child_agent_id, aa.created_at,
       child.id as child_id, child.name as child_name, child.description as child_description,
       child.environment_id
FROM agent_agents aa
JOIN agents child ON aa.child_agent_id = child.id
WHERE aa.parent_agent_id = ?
ORDER BY child.name
`

type ListChildAgentsRow struct {
	ID               int64        `json:"id"`
	ParentAgentID    int64        `json:"parent_agent_id"`
	ChildAgentID     int64        `json:"child_agent_id"`
	CreatedAt        sql.NullTime `json:"created_at"`
	ChildID          int64        `json:"child_id"`
	ChildName        string       `json:"child_name"`
	ChildDescription string       `json:"child_description"`
	EnvironmentID    int64        `json:"environment_id"`
}

func (q *Queries) ListChildAgents(ctx context.Context, parentAgentID int64) ([]ListChildAgentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildAgents, parentAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildAgentsRow
	for rows.Next() {
		var i ListChildAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentAgentID,
			&i.ChildAgentID,
			&i.CreatedAt,
			&i.ChildID,
			&i.ChildName,
			&i.ChildDescription,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentAgents = `-- name: ListParentAgents :many
SELECT aa.id, aa.parent_agent_id, aa.child_agent_id, aa.created_at,
       parent.id as parent_id, parent.name as parent_name, parent.description as parent_description,
       parent.environment_id
FROM agent_agents aa
JOIN agents parent ON aa.parent_agent_id = parent.id
WHERE aa.child_agent_id = ?
ORDER BY parent.name
`

type ListParentAgentsRow struct {
	ID                int64        `json:"id"`
	ParentAgentID     int64        `json:"parent_agent_id"`
	ChildAgentID      int64        `json:"child_agent_id"`
	CreatedAt         sql.NullTime `json:"created_at"`
	ParentID          int64        `json:"parent_id"`
	ParentName        string       `json:"parent_name"`
	ParentDescription string       `json:"parent_description"`
	EnvironmentID     int64        `json:"environment_id"`
}

func (q *Queries) ListParentAgents(ctx context.Context, childAgentID int64) ([]ListParentAgentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listParentAgents, childAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParentAgentsRow
	for rows.Next() {
		var i ListParentAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentAgentID,
			&i.ChildAgentID,
			&i.CreatedAt,
			&i.ParentID,
			&i.ParentName,
			&i.ParentDescription,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChildAgent = `-- name: RemoveChildAgent :exec
DELETE FROM agent_agents WHERE parent_agent_id = ? AND child_agent_id = ?
`

type RemoveChildAgentParams struct {
	ParentAgentID int64 `json:"parent_agent_id"`
	ChildAgentID  int64 `json:"child_agent_id"`
}

func (q *Queries) RemoveChildAgent(ctx context.Context, arg RemoveChildAgentParams) error {
	_, err := q.db.ExecContext(ctx, removeChildAgent, arg.ParentAgentID, arg.ChildAgentID)
	return err
}
