// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mcp_tools.sql

package queries

import (
	"context"
	"database/sql"
)

const createMCPTool = `-- name: CreateMCPTool :one
INSERT INTO mcp_tools (server_id, tool_name, tool_description, tool_schema)
VALUES (?, ?, ?, ?)
RETURNING id, server_id, tool_name, tool_description, tool_schema, created_at
`

type CreateMCPToolParams struct {
	ServerID        int64          `json:"server_id"`
	ToolName        string         `json:"tool_name"`
	ToolDescription sql.NullString `json:"tool_description"`
	ToolSchema      sql.NullString `json:"tool_schema"`
}

func (q *Queries) CreateMCPTool(ctx context.Context, arg CreateMCPToolParams) (McpTool, error) {
	row := q.db.QueryRowContext(ctx, createMCPTool,
		arg.ServerID,
		arg.ToolName,
		arg.ToolDescription,
		arg.ToolSchema,
	)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolSchema,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMCPToolsByServer = `-- name: DeleteMCPToolsByServer :exec
DELETE FROM mcp_tools WHERE server_id = ?
`

func (q *Queries) DeleteMCPToolsByServer(ctx context.Context, serverID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMCPToolsByServer, serverID)
	return err
}

const getMCPTool = `-- name: GetMCPTool :one
SELECT id, server_id, tool_name, tool_description, tool_schema, created_at FROM mcp_tools WHERE id = ?
`

func (q *Queries) GetMCPTool(ctx context.Context, id int64) (McpTool, error) {
	row := q.db.QueryRowContext(ctx, getMCPTool, id)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolSchema,
		&i.CreatedAt,
	)
	return i, err
}

const listMCPToolsByEnvironment = `-- name: ListMCPToolsByEnvironment :many
SELECT t.id, t.server_id, t.tool_name, t.tool_description, t.tool_schema, t.created_at FROM mcp_tools t
JOIN mcp_servers s ON t.server_id = s.id
JOIN mcp_configs c ON s.config_id = c.id
WHERE c.environment_id = ? AND c.version = (
    SELECT MAX(mc.version) FROM mcp_configs mc WHERE mc.environment_id = c.environment_id
)
ORDER BY s.server_name, t.tool_name
`

func (q *Queries) ListMCPToolsByEnvironment(ctx context.Context, environmentID int64) ([]McpTool, error) {
	rows, err := q.db.QueryContext(ctx, listMCPToolsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpTool
	for rows.Next() {
		var i McpTool
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPToolsByServer = `-- name: ListMCPToolsByServer :many
SELECT id, server_id, tool_name, tool_description, tool_schema, created_at FROM mcp_tools WHERE server_id = ? ORDER BY tool_name
`

func (q *Queries) ListMCPToolsByServer(ctx context.Context, serverID int64) ([]McpTool, error) {
	rows, err := q.db.QueryContext(ctx, listMCPToolsByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpTool
	for rows.Next() {
		var i McpTool
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPToolsByServerInEnvironment = `-- name: ListMCPToolsByServerInEnvironment :many
SELECT t.id, t.server_id, t.tool_name, t.tool_description, t.tool_schema, t.created_at FROM mcp_tools t
JOIN mcp_servers s ON t.server_id = s.id
JOIN mcp_configs c ON s.config_id = c.id
WHERE c.environment_id = ? AND s.server_name = ? AND c.version = (
    SELECT MAX(mc.version) FROM mcp_configs mc WHERE mc.environment_id = c.environment_id
)
ORDER BY t.tool_name
`

type ListMCPToolsByServerInEnvironmentParams struct {
	EnvironmentID int64  `json:"environment_id"`
	ServerName    string `json:"server_name"`
}

func (q *Queries) ListMCPToolsByServerInEnvironment(ctx context.Context, arg ListMCPToolsByServerInEnvironmentParams) ([]McpTool, error) {
	rows, err := q.db.QueryContext(ctx, listMCPToolsByServerInEnvironment, arg.EnvironmentID, arg.ServerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpTool
	for rows.Next() {
		var i McpTool
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
