// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Agent struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	Prompt             string         `json:"prompt"`
	MaxSteps           int64          `json:"max_steps"`
	EnvironmentID      int64          `json:"environment_id"`
	CreatedBy          int64          `json:"created_by"`
	ModelID            sql.NullInt64  `json:"model_id"`
	InputSchema        sql.NullString `json:"input_schema"`
	OutputSchema       sql.NullString `json:"output_schema"`
	OutputSchemaPreset sql.NullString `json:"output_schema_preset"`
	App                sql.NullString `json:"app"`
	AppSubtype         sql.NullString `json:"app_subtype"`
	CronSchedule       sql.NullString `json:"cron_schedule"`
	IsScheduled        sql.NullBool   `json:"is_scheduled"`
	LastScheduledRun   sql.NullTime   `json:"last_scheduled_run"`
	NextScheduledRun   sql.NullTime   `json:"next_scheduled_run"`
	ScheduleEnabled    sql.NullBool   `json:"schedule_enabled"`
	ScheduleVariables  sql.NullString `json:"schedule_variables"`
	MemoryTopicKey     sql.NullString `json:"memory_topic_key"`
	MemoryMaxTokens    sql.NullInt64  `json:"memory_max_tokens"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type AgentAgent struct {
	ID            int64        `json:"id"`
	ParentAgentID int64        `json:"parent_agent_id"`
	ChildAgentID  int64        `json:"child_agent_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type AgentReportDetail struct {
	ID                 int64           `json:"id"`
	ReportID           int64           `json:"report_id"`
	AgentID            int64           `json:"agent_id"`
	AgentName          string          `json:"agent_name"`
	Score              float64         `json:"score"`
	Passed             bool            `json:"passed"`
	Reasoning          sql.NullString  `json:"reasoning"`
	CriteriaScores     sql.NullString  `json:"criteria_scores"`
	RunsAnalyzed       sql.NullInt64   `json:"runs_analyzed"`
	RunIds             sql.NullString  `json:"run_ids"`
	AvgDurationSeconds sql.NullFloat64 `json:"avg_duration_seconds"`
	AvgTokens          sql.NullInt64   `json:"avg_tokens"`
	AvgCost            sql.NullFloat64 `json:"avg_cost"`
	SuccessRate        sql.NullFloat64 `json:"success_rate"`
	Strengths          sql.NullString  `json:"strengths"`
	Weaknesses         sql.NullString  `json:"weaknesses"`
	Recommendations    sql.NullString  `json:"recommendations"`
	TelemetrySummary   sql.NullString  `json:"telemetry_summary"`
	BestRunExample     sql.NullString  `json:"best_run_example"`
	WorstRunExample    sql.NullString  `json:"worst_run_example"`
	ToolUsageAnalysis  sql.NullString  `json:"tool_usage_analysis"`
	FailurePatterns    sql.NullString  `json:"failure_patterns"`
	ImprovementPlan    sql.NullString  `json:"improvement_plan"`
	QualityMetrics     sql.NullString  `json:"quality_metrics"`
	CreatedAt          sql.NullTime    `json:"created_at"`
}

type AgentRun struct {
	ID              int64           `json:"id"`
	AgentID         int64           `json:"agent_id"`
	UserID          int64           `json:"user_id"`
	Task            string          `json:"task"`
	FinalResponse   string          `json:"final_response"`
	StepsTaken      int64           `json:"steps_taken"`
	ToolCalls       sql.NullString  `json:"tool_calls"`
	ExecutionSteps  sql.NullString  `json:"execution_steps"`
	Status          string          `json:"status"`
	StartedAt       sql.NullTime    `json:"started_at"`
	CompletedAt     sql.NullTime    `json:"completed_at"`
	InputTokens     sql.NullInt64   `json:"input_tokens"`
	OutputTokens    sql.NullInt64   `json:"output_tokens"`
	TotalTokens     sql.NullInt64   `json:"total_tokens"`
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
	ModelName       sql.NullString  `json:"model_name"`
	ToolsUsed       sql.NullInt64   `json:"tools_used"`
	DebugLogs       sql.NullString  `json:"debug_logs"`
	Error           sql.NullString  `json:"error"`
	ParentRunID     sql.NullInt64   `json:"parent_run_id"`
}

type AgentTool struct {
	ID        int64        `json:"id"`
	AgentID   int64        `json:"agent_id"`
	ToolID    int64        `json:"tool_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Environment struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   int64          `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type FileMcpConfig struct {
	ID                       int64          `json:"id"`
	EnvironmentID            int64          `json:"environment_id"`
	ConfigName               string         `json:"config_name"`
	TemplatePath             string         `json:"template_path"`
	VariablesPath            sql.NullString `json:"variables_path"`
	TemplateSpecificVarsPath sql.NullString `json:"template_specific_vars_path"`
	LastLoadedAt             sql.NullTime   `json:"last_loaded_at"`
	TemplateHash             sql.NullString `json:"template_hash"`
	VariablesHash            sql.NullString `json:"variables_hash"`
	TemplateVarsHash         sql.NullString `json:"template_vars_hash"`
	Metadata                 sql.NullString `json:"metadata"`
	CreatedAt                sql.NullTime   `json:"created_at"`
	UpdatedAt                sql.NullTime   `json:"updated_at"`
}

type McpConfig struct {
	ID              int64          `json:"id"`
	EnvironmentID   int64          `json:"environment_id"`
	ConfigName      string         `json:"config_name"`
	Version         int64          `json:"version"`
	ConfigJson      string         `json:"config_json"`
	EncryptionKeyID sql.NullString `json:"encryption_key_id"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type McpServer struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Command        string         `json:"command"`
	Args           sql.NullString `json:"args"`
	Env            sql.NullString `json:"env"`
	WorkingDir     sql.NullString `json:"working_dir"`
	TimeoutSeconds sql.NullInt64  `json:"timeout_seconds"`
	AutoRestart    sql.NullBool   `json:"auto_restart"`
	EnvironmentID  int64          `json:"environment_id"`
	FileConfigID   sql.NullInt64  `json:"file_config_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type McpTool struct {
	ID           int64          `json:"id"`
	McpServerID  int64          `json:"mcp_server_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	InputSchema  sql.NullString `json:"input_schema"`
	FileConfigID sql.NullInt64  `json:"file_config_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Model struct {
	ID            int64           `json:"id"`
	ProviderID    int64           `json:"provider_id"`
	ModelID       string          `json:"model_id"`
	Name          string          `json:"name"`
	ContextSize   int64           `json:"context_size"`
	MaxTokens     int64           `json:"max_tokens"`
	SupportsTools sql.NullBool    `json:"supports_tools"`
	InputCost     sql.NullFloat64 `json:"input_cost"`
	OutputCost    sql.NullFloat64 `json:"output_cost"`
	Enabled       sql.NullBool    `json:"enabled"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
}

type ModelProvider struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	DisplayName string         `json:"display_name"`
	BaseUrl     string         `json:"base_url"`
	ApiKey      sql.NullString `json:"api_key"`
	Headers     sql.NullString `json:"headers"`
	Enabled     sql.NullBool   `json:"enabled"`
	IsDefault   sql.NullBool   `json:"is_default"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Report struct {
	ID                        int64           `json:"id"`
	Name                      string          `json:"name"`
	Description               sql.NullString  `json:"description"`
	EnvironmentID             int64           `json:"environment_id"`
	TeamCriteria              string          `json:"team_criteria"`
	AgentCriteria             sql.NullString  `json:"agent_criteria"`
	Status                    string          `json:"status"`
	Progress                  sql.NullInt64   `json:"progress"`
	CurrentStep               sql.NullString  `json:"current_step"`
	ExecutiveSummary          sql.NullString  `json:"executive_summary"`
	TeamScore                 sql.NullFloat64 `json:"team_score"`
	TeamReasoning             sql.NullString  `json:"team_reasoning"`
	TeamCriteriaScores        sql.NullString  `json:"team_criteria_scores"`
	AgentReports              sql.NullString  `json:"agent_reports"`
	TotalRunsAnalyzed         sql.NullInt64   `json:"total_runs_analyzed"`
	TotalAgentsAnalyzed       sql.NullInt64   `json:"total_agents_analyzed"`
	GenerationDurationSeconds sql.NullFloat64 `json:"generation_duration_seconds"`
	GenerationStartedAt       sql.NullTime    `json:"generation_started_at"`
	GenerationCompletedAt     sql.NullTime    `json:"generation_completed_at"`
	TotalLlmTokens            sql.NullInt64   `json:"total_llm_tokens"`
	TotalLlmCost              sql.NullFloat64 `json:"total_llm_cost"`
	JudgeModel                sql.NullString  `json:"judge_model"`
	FilterModel               sql.NullString  `json:"filter_model"`
	ErrorMessage              sql.NullString  `json:"error_message"`
	CreatedAt                 sql.NullTime    `json:"created_at"`
	UpdatedAt                 sql.NullTime    `json:"updated_at"`
}

type Setting struct {
	ID          int64          `json:"id"`
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Theme struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	DisplayName string         `json:"display_name"`
	Description sql.NullString `json:"description"`
	IsBuiltIn   sql.NullBool   `json:"is_built_in"`
	IsDefault   sql.NullBool   `json:"is_default"`
	CreatedBy   sql.NullInt64  `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ThemeColor struct {
	ID          int64          `json:"id"`
	ThemeID     int64          `json:"theme_id"`
	ColorKey    string         `json:"color_key"`
	ColorValue  string         `json:"color_value"`
	Description sql.NullString `json:"description"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	PublicKey string         `json:"public_key"`
	IsAdmin   bool           `json:"is_admin"`
	ApiKey    sql.NullString `json:"api_key"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type UserThemePreference struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	ThemeID   int64        `json:"theme_id"`
	AppliedAt sql.NullTime `json:"applied_at"`
}

type Webhook struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Url            string         `json:"url"`
	Secret         sql.NullString `json:"secret"`
	Enabled        sql.NullBool   `json:"enabled"`
	Events         string         `json:"events"`
	Headers        sql.NullString `json:"headers"`
	TimeoutSeconds sql.NullInt64  `json:"timeout_seconds"`
	RetryAttempts  sql.NullInt64  `json:"retry_attempts"`
	CreatedBy      int64          `json:"created_by"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type WebhookDelivery struct {
	ID              int64          `json:"id"`
	WebhookID       int64          `json:"webhook_id"`
	EventType       string         `json:"event_type"`
	Payload         string         `json:"payload"`
	Status          string         `json:"status"`
	HttpStatusCode  sql.NullInt64  `json:"http_status_code"`
	ResponseBody    sql.NullString `json:"response_body"`
	ResponseHeaders sql.NullString `json:"response_headers"`
	ErrorMessage    sql.NullString `json:"error_message"`
	AttemptCount    sql.NullInt64  `json:"attempt_count"`
	LastAttemptAt   sql.NullTime   `json:"last_attempt_at"`
	NextRetryAt     sql.NullTime   `json:"next_retry_at"`
	DeliveredAt     sql.NullTime   `json:"delivered_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Workflow struct {
	ID          int64          `json:"id"`
	WorkflowID  string         `json:"workflow_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Version     int64          `json:"version"`
	Definition  string         `json:"definition"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type WorkflowApproval struct {
	ID             int64          `json:"id"`
	ApprovalID     string         `json:"approval_id"`
	RunID          string         `json:"run_id"`
	StepID         string         `json:"step_id"`
	Message        string         `json:"message"`
	SummaryPath    sql.NullString `json:"summary_path"`
	Approvers      sql.NullString `json:"approvers"`
	Status         string         `json:"status"`
	DecidedBy      sql.NullString `json:"decided_by"`
	DecidedAt      sql.NullTime   `json:"decided_at"`
	DecisionReason sql.NullString `json:"decision_reason"`
	TimeoutAt      sql.NullTime   `json:"timeout_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type WorkflowRun struct {
	ID              int64          `json:"id"`
	RunID           string         `json:"run_id"`
	WorkflowID      string         `json:"workflow_id"`
	WorkflowVersion int64          `json:"workflow_version"`
	Status          string         `json:"status"`
	CurrentStep     sql.NullString `json:"current_step"`
	Input           sql.NullString `json:"input"`
	Context         sql.NullString `json:"context"`
	Result          sql.NullString `json:"result"`
	Error           sql.NullString `json:"error"`
	Summary         sql.NullString `json:"summary"`
	Options         sql.NullString `json:"options"`
	LastSignal      sql.NullString `json:"last_signal"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
}

type WorkflowRunEvent struct {
	ID        int64          `json:"id"`
	RunID     string         `json:"run_id"`
	Seq       int64          `json:"seq"`
	EventType string         `json:"event_type"`
	StepID    sql.NullString `json:"step_id"`
	Payload   sql.NullString `json:"payload"`
	Actor     sql.NullString `json:"actor"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type WorkflowRunStep struct {
	ID          int64          `json:"id"`
	RunID       string         `json:"run_id"`
	StepID      string         `json:"step_id"`
	Attempt     int64          `json:"attempt"`
	Status      string         `json:"status"`
	Input       sql.NullString `json:"input"`
	Output      sql.NullString `json:"output"`
	Error       sql.NullString `json:"error"`
	Metadata    sql.NullString `json:"metadata"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type WorkflowSchedule struct {
	ID              int64          `json:"id"`
	WorkflowID      string         `json:"workflow_id"`
	WorkflowVersion int64          `json:"workflow_version"`
	CronExpression  string         `json:"cron_expression"`
	Timezone        string         `json:"timezone"`
	Enabled         bool           `json:"enabled"`
	Input           sql.NullString `json:"input"`
	LastRunAt       sql.NullTime   `json:"last_run_at"`
	NextRunAt       sql.NullTime   `json:"next_run_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}
