// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
)

type Agent struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	Prompt           string         `json:"prompt"`
	MaxSteps         int64          `json:"max_steps"`
	EnvironmentID    int64          `json:"environment_id"`
	CreatedBy        int64          `json:"created_by"`
	ModelID          sql.NullInt64  `json:"model_id"`
	CronSchedule     sql.NullString `json:"cron_schedule"`
	IsScheduled      sql.NullBool   `json:"is_scheduled"`
	LastScheduledRun sql.NullTime   `json:"last_scheduled_run"`
	NextScheduledRun sql.NullTime   `json:"next_scheduled_run"`
	ScheduleEnabled  sql.NullBool   `json:"schedule_enabled"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type AgentEnvironment struct {
	ID            int64        `json:"id"`
	AgentID       int64        `json:"agent_id"`
	EnvironmentID int64        `json:"environment_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type AgentRun struct {
	ID             int64          `json:"id"`
	AgentID        int64          `json:"agent_id"`
	UserID         int64          `json:"user_id"`
	Task           string         `json:"task"`
	FinalResponse  string         `json:"final_response"`
	StepsTaken     int64          `json:"steps_taken"`
	ToolCalls      sql.NullString `json:"tool_calls"`
	ExecutionSteps sql.NullString `json:"execution_steps"`
	Status         string         `json:"status"`
	StartedAt      sql.NullTime   `json:"started_at"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
}

type AgentTool struct {
	ID            int64        `json:"id"`
	AgentID       int64        `json:"agent_id"`
	ToolName      string       `json:"tool_name"`
	EnvironmentID int64        `json:"environment_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type Environment struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   int64          `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type McpConfig struct {
	ID              int64          `json:"id"`
	EnvironmentID   int64          `json:"environment_id"`
	ConfigName      string         `json:"config_name"`
	Version         int64          `json:"version"`
	ConfigJson      string         `json:"config_json"`
	EncryptionKeyID sql.NullString `json:"encryption_key_id"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type McpServer struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Command        string         `json:"command"`
	Args           sql.NullString `json:"args"`
	Env            sql.NullString `json:"env"`
	WorkingDir     sql.NullString `json:"working_dir"`
	TimeoutSeconds sql.NullInt64  `json:"timeout_seconds"`
	AutoRestart    sql.NullBool   `json:"auto_restart"`
	EnvironmentID  int64          `json:"environment_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type McpTool struct {
	ID          int64          `json:"id"`
	McpServerID int64          `json:"mcp_server_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	InputSchema sql.NullString `json:"input_schema"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Model struct {
	ID            int64           `json:"id"`
	ProviderID    int64           `json:"provider_id"`
	ModelID       string          `json:"model_id"`
	Name          string          `json:"name"`
	ContextSize   int64           `json:"context_size"`
	MaxTokens     int64           `json:"max_tokens"`
	SupportsTools sql.NullBool    `json:"supports_tools"`
	InputCost     sql.NullFloat64 `json:"input_cost"`
	OutputCost    sql.NullFloat64 `json:"output_cost"`
	Enabled       sql.NullBool    `json:"enabled"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
}

type ModelProvider struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	DisplayName string         `json:"display_name"`
	BaseUrl     string         `json:"base_url"`
	ApiKey      sql.NullString `json:"api_key"`
	Headers     sql.NullString `json:"headers"`
	Enabled     sql.NullBool   `json:"enabled"`
	IsDefault   sql.NullBool   `json:"is_default"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	IsAdmin   bool           `json:"is_admin"`
	ApiKey    sql.NullString `json:"api_key"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
