// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package queries

import (
	"context"
	"database/sql"
)

const completeReport = `-- name: CompleteReport :exec
UPDATE reports
SET status = 'completed',
    progress = 100,
    generation_completed_at = CURRENT_TIMESTAMP,
    generation_duration_seconds = ?,
    total_runs_analyzed = ?,
    total_agents_analyzed = ?,
    total_llm_tokens = ?,
    total_llm_cost = ?,
    agent_reports = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type CompleteReportParams struct {
	GenerationDurationSeconds sql.NullFloat64 `json:"generation_duration_seconds"`
	TotalRunsAnalyzed         sql.NullInt64   `json:"total_runs_analyzed"`
	TotalAgentsAnalyzed       sql.NullInt64   `json:"total_agents_analyzed"`
	TotalLlmTokens            sql.NullInt64   `json:"total_llm_tokens"`
	TotalLlmCost              sql.NullFloat64 `json:"total_llm_cost"`
	AgentReports              sql.NullString  `json:"agent_reports"`
	ID                        int64           `json:"id"`
}

func (q *Queries) CompleteReport(ctx context.Context, arg CompleteReportParams) error {
	_, err := q.db.ExecContext(ctx, completeReport,
		arg.GenerationDurationSeconds,
		arg.TotalRunsAnalyzed,
		arg.TotalAgentsAnalyzed,
		arg.TotalLlmTokens,
		arg.TotalLlmCost,
		arg.AgentReports,
		arg.ID,
	)
	return err
}

const countReportsByEnvironment = `-- name: CountReportsByEnvironment :one
SELECT COUNT(*) FROM reports WHERE environment_id = ?
`

func (q *Queries) CountReportsByEnvironment(ctx context.Context, environmentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReportsByEnvironment, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentReportDetail = `-- name: CreateAgentReportDetail :one
INSERT INTO agent_report_details (
    report_id,
    agent_id,
    agent_name,
    score,
    passed,
    reasoning,
    criteria_scores,
    runs_analyzed,
    run_ids,
    avg_duration_seconds,
    avg_tokens,
    avg_cost,
    success_rate,
    strengths,
    weaknesses,
    recommendations,
    telemetry_summary,
    best_run_example,
    worst_run_example,
    tool_usage_analysis,
    failure_patterns,
    improvement_plan,
    quality_metrics
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, report_id, agent_id, agent_name, score, passed, reasoning, criteria_scores, runs_analyzed, run_ids, avg_duration_seconds, avg_tokens, avg_cost, success_rate, strengths, weaknesses, recommendations, telemetry_summary, best_run_example, worst_run_example, tool_usage_analysis, failure_patterns, improvement_plan, quality_metrics, created_at
`

type CreateAgentReportDetailParams struct {
	ReportID           int64           `json:"report_id"`
	AgentID            int64           `json:"agent_id"`
	AgentName          string          `json:"agent_name"`
	Score              float64         `json:"score"`
	Passed             bool            `json:"passed"`
	Reasoning          sql.NullString  `json:"reasoning"`
	CriteriaScores     sql.NullString  `json:"criteria_scores"`
	RunsAnalyzed       sql.NullInt64   `json:"runs_analyzed"`
	RunIds             sql.NullString  `json:"run_ids"`
	AvgDurationSeconds sql.NullFloat64 `json:"avg_duration_seconds"`
	AvgTokens          sql.NullInt64   `json:"avg_tokens"`
	AvgCost            sql.NullFloat64 `json:"avg_cost"`
	SuccessRate        sql.NullFloat64 `json:"success_rate"`
	Strengths          sql.NullString  `json:"strengths"`
	Weaknesses         sql.NullString  `json:"weaknesses"`
	Recommendations    sql.NullString  `json:"recommendations"`
	TelemetrySummary   sql.NullString  `json:"telemetry_summary"`
	BestRunExample     sql.NullString  `json:"best_run_example"`
	WorstRunExample    sql.NullString  `json:"worst_run_example"`
	ToolUsageAnalysis  sql.NullString  `json:"tool_usage_analysis"`
	FailurePatterns    sql.NullString  `json:"failure_patterns"`
	ImprovementPlan    sql.NullString  `json:"improvement_plan"`
	QualityMetrics     sql.NullString  `json:"quality_metrics"`
}

func (q *Queries) CreateAgentReportDetail(ctx context.Context, arg CreateAgentReportDetailParams) (AgentReportDetail, error) {
	row := q.db.QueryRowContext(ctx, createAgentReportDetail,
		arg.ReportID,
		arg.AgentID,
		arg.AgentName,
		arg.Score,
		arg.Passed,
		arg.Reasoning,
		arg.CriteriaScores,
		arg.RunsAnalyzed,
		arg.RunIds,
		arg.AvgDurationSeconds,
		arg.AvgTokens,
		arg.AvgCost,
		arg.SuccessRate,
		arg.Strengths,
		arg.Weaknesses,
		arg.Recommendations,
		arg.TelemetrySummary,
		arg.BestRunExample,
		arg.WorstRunExample,
		arg.ToolUsageAnalysis,
		arg.FailurePatterns,
		arg.ImprovementPlan,
		arg.QualityMetrics,
	)
	var i AgentReportDetail
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AgentID,
		&i.AgentName,
		&i.Score,
		&i.Passed,
		&i.Reasoning,
		&i.CriteriaScores,
		&i.RunsAnalyzed,
		&i.RunIds,
		&i.AvgDurationSeconds,
		&i.AvgTokens,
		&i.AvgCost,
		&i.SuccessRate,
		&i.Strengths,
		&i.Weaknesses,
		&i.Recommendations,
		&i.TelemetrySummary,
		&i.BestRunExample,
		&i.WorstRunExample,
		&i.ToolUsageAnalysis,
		&i.FailurePatterns,
		&i.ImprovementPlan,
		&i.QualityMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    name,
    description,
    environment_id,
    team_criteria,
    agent_criteria,
    judge_model,
    filter_model
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, environment_id, team_criteria, agent_criteria, status, progress, current_step, executive_summary, team_score, team_reasoning, team_criteria_scores, agent_reports, total_runs_analyzed, total_agents_analyzed, generation_duration_seconds, generation_started_at, generation_completed_at, total_llm_tokens, total_llm_cost, judge_model, filter_model, error_message, created_at, updated_at
`

type CreateReportParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	EnvironmentID int64          `json:"environment_id"`
	TeamCriteria  string         `json:"team_criteria"`
	AgentCriteria sql.NullString `json:"agent_criteria"`
	JudgeModel    sql.NullString `json:"judge_model"`
	FilterModel   sql.NullString `json:"filter_model"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.Name,
		arg.Description,
		arg.EnvironmentID,
		arg.TeamCriteria,
		arg.AgentCriteria,
		arg.JudgeModel,
		arg.FilterModel,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EnvironmentID,
		&i.TeamCriteria,
		&i.AgentCriteria,
		&i.Status,
		&i.Progress,
		&i.CurrentStep,
		&i.ExecutiveSummary,
		&i.TeamScore,
		&i.TeamReasoning,
		&i.TeamCriteriaScores,
		&i.AgentReports,
		&i.TotalRunsAnalyzed,
		&i.TotalAgentsAnalyzed,
		&i.GenerationDurationSeconds,
		&i.GenerationStartedAt,
		&i.GenerationCompletedAt,
		&i.TotalLlmTokens,
		&i.TotalLlmCost,
		&i.JudgeModel,
		&i.FilterModel,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentReportDetails = `-- name: DeleteAgentReportDetails :exec
DELETE FROM agent_report_details WHERE report_id = ?
`

func (q *Queries) DeleteAgentReportDetails(ctx context.Context, reportID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAgentReportDetails, reportID)
	return err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = ?
`

func (q *Queries) DeleteReport(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReport, id)
	return err
}

const failReport = `-- name: FailReport :exec
UPDATE reports
SET status = 'failed',
    error_message = ?,
    generation_completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type FailReportParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) FailReport(ctx context.Context, arg FailReportParams) error {
	_, err := q.db.ExecContext(ctx, failReport, arg.ErrorMessage, arg.ID)
	return err
}

const getAgentReportDetail = `-- name: GetAgentReportDetail :one
SELECT id, report_id, agent_id, agent_name, score, passed, reasoning, criteria_scores, runs_analyzed, run_ids, avg_duration_seconds, avg_tokens, avg_cost, success_rate, strengths, weaknesses, recommendations, telemetry_summary, best_run_example, worst_run_example, tool_usage_analysis, failure_patterns, improvement_plan, quality_metrics, created_at FROM agent_report_details WHERE id = ?
`

func (q *Queries) GetAgentReportDetail(ctx context.Context, id int64) (AgentReportDetail, error) {
	row := q.db.QueryRowContext(ctx, getAgentReportDetail, id)
	var i AgentReportDetail
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AgentID,
		&i.AgentName,
		&i.Score,
		&i.Passed,
		&i.Reasoning,
		&i.CriteriaScores,
		&i.RunsAnalyzed,
		&i.RunIds,
		&i.AvgDurationSeconds,
		&i.AvgTokens,
		&i.AvgCost,
		&i.SuccessRate,
		&i.Strengths,
		&i.Weaknesses,
		&i.Recommendations,
		&i.TelemetrySummary,
		&i.BestRunExample,
		&i.WorstRunExample,
		&i.ToolUsageAnalysis,
		&i.FailurePatterns,
		&i.ImprovementPlan,
		&i.QualityMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentReportDetailByAgentID = `-- name: GetAgentReportDetailByAgentID :one
SELECT id, report_id, agent_id, agent_name, score, passed, reasoning, criteria_scores, runs_analyzed, run_ids, avg_duration_seconds, avg_tokens, avg_cost, success_rate, strengths, weaknesses, recommendations, telemetry_summary, best_run_example, worst_run_example, tool_usage_analysis, failure_patterns, improvement_plan, quality_metrics, created_at FROM agent_report_details WHERE report_id = ? AND agent_id = ?
`

type GetAgentReportDetailByAgentIDParams struct {
	ReportID int64 `json:"report_id"`
	AgentID  int64 `json:"agent_id"`
}

func (q *Queries) GetAgentReportDetailByAgentID(ctx context.Context, arg GetAgentReportDetailByAgentIDParams) (AgentReportDetail, error) {
	row := q.db.QueryRowContext(ctx, getAgentReportDetailByAgentID, arg.ReportID, arg.AgentID)
	var i AgentReportDetail
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AgentID,
		&i.AgentName,
		&i.Score,
		&i.Passed,
		&i.Reasoning,
		&i.CriteriaScores,
		&i.RunsAnalyzed,
		&i.RunIds,
		&i.AvgDurationSeconds,
		&i.AvgTokens,
		&i.AvgCost,
		&i.SuccessRate,
		&i.Strengths,
		&i.Weaknesses,
		&i.Recommendations,
		&i.TelemetrySummary,
		&i.BestRunExample,
		&i.WorstRunExample,
		&i.ToolUsageAnalysis,
		&i.FailurePatterns,
		&i.ImprovementPlan,
		&i.QualityMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentReportDetails = `-- name: GetAgentReportDetails :many
SELECT id, report_id, agent_id, agent_name, score, passed, reasoning, criteria_scores, runs_analyzed, run_ids, avg_duration_seconds, avg_tokens, avg_cost, success_rate, strengths, weaknesses, recommendations, telemetry_summary, best_run_example, worst_run_example, tool_usage_analysis, failure_patterns, improvement_plan, quality_metrics, created_at FROM agent_report_details WHERE report_id = ? ORDER BY score DESC
`

func (q *Queries) GetAgentReportDetails(ctx context.Context, reportID int64) ([]AgentReportDetail, error) {
	rows, err := q.db.QueryContext(ctx, getAgentReportDetails, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentReportDetail
	for rows.Next() {
		var i AgentReportDetail
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.AgentID,
			&i.AgentName,
			&i.Score,
			&i.Passed,
			&i.Reasoning,
			&i.CriteriaScores,
			&i.RunsAnalyzed,
			&i.RunIds,
			&i.AvgDurationSeconds,
			&i.AvgTokens,
			&i.AvgCost,
			&i.SuccessRate,
			&i.Strengths,
			&i.Weaknesses,
			&i.Recommendations,
			&i.TelemetrySummary,
			&i.BestRunExample,
			&i.WorstRunExample,
			&i.ToolUsageAnalysis,
			&i.FailurePatterns,
			&i.ImprovementPlan,
			&i.QualityMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestReportByEnvironment = `-- name: GetLatestReportByEnvironment :one
SELECT id, name, description, environment_id, team_criteria, agent_criteria, status, progress, current_step, executive_summary, team_score, team_reasoning, team_criteria_scores, agent_reports, total_runs_analyzed, total_agents_analyzed, generation_duration_seconds, generation_started_at, generation_completed_at, total_llm_tokens, total_llm_cost, judge_model, filter_model, error_message, created_at, updated_at FROM reports 
WHERE environment_id = ? 
ORDER BY created_at DESC 
LIMIT 1
`

func (q *Queries) GetLatestReportByEnvironment(ctx context.Context, environmentID int64) (Report, error) {
	row := q.db.QueryRowContext(ctx, getLatestReportByEnvironment, environmentID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EnvironmentID,
		&i.TeamCriteria,
		&i.AgentCriteria,
		&i.Status,
		&i.Progress,
		&i.CurrentStep,
		&i.ExecutiveSummary,
		&i.TeamScore,
		&i.TeamReasoning,
		&i.TeamCriteriaScores,
		&i.AgentReports,
		&i.TotalRunsAnalyzed,
		&i.TotalAgentsAnalyzed,
		&i.GenerationDurationSeconds,
		&i.GenerationStartedAt,
		&i.GenerationCompletedAt,
		&i.TotalLlmTokens,
		&i.TotalLlmCost,
		&i.JudgeModel,
		&i.FilterModel,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, name, description, environment_id, team_criteria, agent_criteria, status, progress, current_step, executive_summary, team_score, team_reasoning, team_criteria_scores, agent_reports, total_runs_analyzed, total_agents_analyzed, generation_duration_seconds, generation_started_at, generation_completed_at, total_llm_tokens, total_llm_cost, judge_model, filter_model, error_message, created_at, updated_at FROM reports WHERE id = ?
`

func (q *Queries) GetReport(ctx context.Context, id int64) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.EnvironmentID,
		&i.TeamCriteria,
		&i.AgentCriteria,
		&i.Status,
		&i.Progress,
		&i.CurrentStep,
		&i.ExecutiveSummary,
		&i.TeamScore,
		&i.TeamReasoning,
		&i.TeamCriteriaScores,
		&i.AgentReports,
		&i.TotalRunsAnalyzed,
		&i.TotalAgentsAnalyzed,
		&i.GenerationDurationSeconds,
		&i.GenerationStartedAt,
		&i.GenerationCompletedAt,
		&i.TotalLlmTokens,
		&i.TotalLlmCost,
		&i.JudgeModel,
		&i.FilterModel,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, name, description, environment_id, team_criteria, agent_criteria, status, progress, current_step, executive_summary, team_score, team_reasoning, team_criteria_scores, agent_reports, total_runs_analyzed, total_agents_analyzed, generation_duration_seconds, generation_started_at, generation_completed_at, total_llm_tokens, total_llm_cost, judge_model, filter_model, error_message, created_at, updated_at FROM reports ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListReportsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.EnvironmentID,
			&i.TeamCriteria,
			&i.AgentCriteria,
			&i.Status,
			&i.Progress,
			&i.CurrentStep,
			&i.ExecutiveSummary,
			&i.TeamScore,
			&i.TeamReasoning,
			&i.TeamCriteriaScores,
			&i.AgentReports,
			&i.TotalRunsAnalyzed,
			&i.TotalAgentsAnalyzed,
			&i.GenerationDurationSeconds,
			&i.GenerationStartedAt,
			&i.GenerationCompletedAt,
			&i.TotalLlmTokens,
			&i.TotalLlmCost,
			&i.JudgeModel,
			&i.FilterModel,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByEnvironment = `-- name: ListReportsByEnvironment :many
SELECT id, name, description, environment_id, team_criteria, agent_criteria, status, progress, current_step, executive_summary, team_score, team_reasoning, team_criteria_scores, agent_reports, total_runs_analyzed, total_agents_analyzed, generation_duration_seconds, generation_started_at, generation_completed_at, total_llm_tokens, total_llm_cost, judge_model, filter_model, error_message, created_at, updated_at FROM reports WHERE environment_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListReportsByEnvironment(ctx context.Context, environmentID int64) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.EnvironmentID,
			&i.TeamCriteria,
			&i.AgentCriteria,
			&i.Status,
			&i.Progress,
			&i.CurrentStep,
			&i.ExecutiveSummary,
			&i.TeamScore,
			&i.TeamReasoning,
			&i.TeamCriteriaScores,
			&i.AgentReports,
			&i.TotalRunsAnalyzed,
			&i.TotalAgentsAnalyzed,
			&i.GenerationDurationSeconds,
			&i.GenerationStartedAt,
			&i.GenerationCompletedAt,
			&i.TotalLlmTokens,
			&i.TotalLlmCost,
			&i.JudgeModel,
			&i.FilterModel,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReportGenerationStarted = `-- name: SetReportGenerationStarted :exec
UPDATE reports
SET generation_started_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SetReportGenerationStarted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setReportGenerationStarted, id)
	return err
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports 
SET status = ?,
    progress = ?,
    current_step = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReportStatusParams struct {
	Status      string         `json:"status"`
	Progress    sql.NullInt64  `json:"progress"`
	CurrentStep sql.NullString `json:"current_step"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReportStatus,
		arg.Status,
		arg.Progress,
		arg.CurrentStep,
		arg.ID,
	)
	return err
}

const updateReportTeamResults = `-- name: UpdateReportTeamResults :exec
UPDATE reports
SET executive_summary = ?,
    team_score = ?,
    team_reasoning = ?,
    team_criteria_scores = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReportTeamResultsParams struct {
	ExecutiveSummary   sql.NullString  `json:"executive_summary"`
	TeamScore          sql.NullFloat64 `json:"team_score"`
	TeamReasoning      sql.NullString  `json:"team_reasoning"`
	TeamCriteriaScores sql.NullString  `json:"team_criteria_scores"`
	ID                 int64           `json:"id"`
}

func (q *Queries) UpdateReportTeamResults(ctx context.Context, arg UpdateReportTeamResultsParams) error {
	_, err := q.db.ExecContext(ctx, updateReportTeamResults,
		arg.ExecutiveSummary,
		arg.TeamScore,
		arg.TeamReasoning,
		arg.TeamCriteriaScores,
		arg.ID,
	)
	return err
}
