// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_run_events.sql

package queries

import (
	"context"
	"database/sql"
)

const getNextEventSeq = `-- name: GetNextEventSeq :one
SELECT COALESCE(MAX(seq), 0) + 1 AS next_seq
FROM workflow_run_events
WHERE run_id = ?1
`

func (q *Queries) GetNextEventSeq(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextEventSeq, runID)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const insertWorkflowRunEvent = `-- name: InsertWorkflowRunEvent :one
INSERT INTO workflow_run_events (
    run_id,
    seq,
    event_type,
    step_id,
    payload,
    actor
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
RETURNING id, run_id, seq, event_type, step_id, payload, actor, created_at
`

type InsertWorkflowRunEventParams struct {
	RunID     string         `json:"run_id"`
	Seq       int64          `json:"seq"`
	EventType string         `json:"event_type"`
	StepID    sql.NullString `json:"step_id"`
	Payload   sql.NullString `json:"payload"`
	Actor     sql.NullString `json:"actor"`
}

func (q *Queries) InsertWorkflowRunEvent(ctx context.Context, arg InsertWorkflowRunEventParams) (WorkflowRunEvent, error) {
	row := q.db.QueryRowContext(ctx, insertWorkflowRunEvent,
		arg.RunID,
		arg.Seq,
		arg.EventType,
		arg.StepID,
		arg.Payload,
		arg.Actor,
	)
	var i WorkflowRunEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.EventType,
		&i.StepID,
		&i.Payload,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkflowRunEvents = `-- name: ListWorkflowRunEvents :many
SELECT id, run_id, seq, event_type, step_id, payload, actor, created_at
FROM workflow_run_events
WHERE run_id = ?1
ORDER BY seq ASC
`

func (q *Queries) ListWorkflowRunEvents(ctx context.Context, runID string) ([]WorkflowRunEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRunEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRunEvent
	for rows.Next() {
		var i WorkflowRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.EventType,
			&i.StepID,
			&i.Payload,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunEventsByType = `-- name: ListWorkflowRunEventsByType :many
SELECT id, run_id, seq, event_type, step_id, payload, actor, created_at
FROM workflow_run_events
WHERE run_id = ?1
  AND event_type = ?2
ORDER BY seq ASC
`

type ListWorkflowRunEventsByTypeParams struct {
	RunID     string `json:"run_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) ListWorkflowRunEventsByType(ctx context.Context, arg ListWorkflowRunEventsByTypeParams) ([]WorkflowRunEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRunEventsByType, arg.RunID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRunEvent
	for rows.Next() {
		var i WorkflowRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.EventType,
			&i.StepID,
			&i.Payload,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
