// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package queries

import (
	"context"
	"database/sql"
)

const deleteAllWorkflows = `-- name: DeleteAllWorkflows :exec
DELETE FROM workflows
`

func (q *Queries) DeleteAllWorkflows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllWorkflows)
	return err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows WHERE workflow_id = ?1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, workflowID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflow, workflowID)
	return err
}

const disableWorkflow = `-- name: DisableWorkflow :exec
UPDATE workflows
SET status = 'disabled', updated_at = CURRENT_TIMESTAMP
WHERE workflow_id = ?1
`

func (q *Queries) DisableWorkflow(ctx context.Context, workflowID string) error {
	_, err := q.db.ExecContext(ctx, disableWorkflow, workflowID)
	return err
}

const getLatestWorkflow = `-- name: GetLatestWorkflow :one
SELECT id, workflow_id, name, description, version, definition, status, created_at, updated_at
FROM workflows
WHERE workflow_id = ?1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestWorkflow(ctx context.Context, workflowID string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getLatestWorkflow, workflowID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Definition,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextWorkflowVersion = `-- name: GetNextWorkflowVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM workflows
WHERE workflow_id = ?1
`

func (q *Queries) GetNextWorkflowVersion(ctx context.Context, workflowID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextWorkflowVersion, workflowID)
	var next_version int64
	err := row.Scan(&next_version)
	return next_version, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, workflow_id, name, description, version, definition, status, created_at, updated_at
FROM workflows
WHERE workflow_id = ?1 AND version = ?2
`

type GetWorkflowParams struct {
	WorkflowID string `json:"workflow_id"`
	Version    int64  `json:"version"`
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, arg.WorkflowID, arg.Version)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Definition,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkflow = `-- name: InsertWorkflow :one
INSERT INTO workflows (workflow_id, name, description, version, definition, status)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, workflow_id, name, description, version, definition, status, created_at, updated_at
`

type InsertWorkflowParams struct {
	WorkflowID  string         `json:"workflow_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Version     int64          `json:"version"`
	Definition  string         `json:"definition"`
	Status      string         `json:"status"`
}

func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, insertWorkflow,
		arg.WorkflowID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Definition,
		arg.Status,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Definition,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLatestWorkflows = `-- name: ListLatestWorkflows :many
WITH latest AS (
    SELECT workflow_id, MAX(version) AS version
    FROM workflows
    GROUP BY workflow_id
)
SELECT w.id, w.workflow_id, w.name, w.description, w.version, w.definition, w.status, w.created_at, w.updated_at
FROM workflows w
JOIN latest l ON w.workflow_id = l.workflow_id AND w.version = l.version
ORDER BY w.workflow_id
`

func (q *Queries) ListLatestWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Definition,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersions = `-- name: ListWorkflowVersions :many
SELECT id, workflow_id, name, description, version, definition, status, created_at, updated_at
FROM workflows
WHERE workflow_id = ?1
ORDER BY version DESC
`

func (q *Queries) ListWorkflowVersions(ctx context.Context, workflowID string) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowVersions, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Definition,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
