// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_schedules.sql

package queries

import (
	"context"
	"database/sql"
)

const createWorkflowSchedule = `-- name: CreateWorkflowSchedule :one
INSERT INTO workflow_schedules (
    workflow_id,
    workflow_version,
    cron_expression,
    timezone,
    enabled,
    input,
    next_run_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, workflow_id, workflow_version, cron_expression, timezone, enabled, input, last_run_at, next_run_at, created_at, updated_at
`

type CreateWorkflowScheduleParams struct {
	WorkflowID      string         `json:"workflow_id"`
	WorkflowVersion int64          `json:"workflow_version"`
	CronExpression  string         `json:"cron_expression"`
	Timezone        string         `json:"timezone"`
	Enabled         bool           `json:"enabled"`
	Input           sql.NullString `json:"input"`
	NextRunAt       sql.NullTime   `json:"next_run_at"`
}

func (q *Queries) CreateWorkflowSchedule(ctx context.Context, arg CreateWorkflowScheduleParams) (WorkflowSchedule, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowSchedule,
		arg.WorkflowID,
		arg.WorkflowVersion,
		arg.CronExpression,
		arg.Timezone,
		arg.Enabled,
		arg.Input,
		arg.NextRunAt,
	)
	var i WorkflowSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.CronExpression,
		&i.Timezone,
		&i.Enabled,
		&i.Input,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflowSchedule = `-- name: DeleteWorkflowSchedule :exec
DELETE FROM workflow_schedules
WHERE workflow_id = ? AND workflow_version = ?
`

type DeleteWorkflowScheduleParams struct {
	WorkflowID      string `json:"workflow_id"`
	WorkflowVersion int64  `json:"workflow_version"`
}

func (q *Queries) DeleteWorkflowSchedule(ctx context.Context, arg DeleteWorkflowScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowSchedule, arg.WorkflowID, arg.WorkflowVersion)
	return err
}

const deleteWorkflowScheduleByWorkflowID = `-- name: DeleteWorkflowScheduleByWorkflowID :exec
DELETE FROM workflow_schedules
WHERE workflow_id = ?
`

func (q *Queries) DeleteWorkflowScheduleByWorkflowID(ctx context.Context, workflowID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowScheduleByWorkflowID, workflowID)
	return err
}

const getWorkflowSchedule = `-- name: GetWorkflowSchedule :one
SELECT id, workflow_id, workflow_version, cron_expression, timezone, enabled, input, last_run_at, next_run_at, created_at, updated_at FROM workflow_schedules
WHERE workflow_id = ? AND workflow_version = ?
`

type GetWorkflowScheduleParams struct {
	WorkflowID      string `json:"workflow_id"`
	WorkflowVersion int64  `json:"workflow_version"`
}

func (q *Queries) GetWorkflowSchedule(ctx context.Context, arg GetWorkflowScheduleParams) (WorkflowSchedule, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowSchedule, arg.WorkflowID, arg.WorkflowVersion)
	var i WorkflowSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.CronExpression,
		&i.Timezone,
		&i.Enabled,
		&i.Input,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowScheduleByID = `-- name: GetWorkflowScheduleByID :one
SELECT id, workflow_id, workflow_version, cron_expression, timezone, enabled, input, last_run_at, next_run_at, created_at, updated_at FROM workflow_schedules
WHERE id = ?
`

func (q *Queries) GetWorkflowScheduleByID(ctx context.Context, id int64) (WorkflowSchedule, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowScheduleByID, id)
	var i WorkflowSchedule
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.CronExpression,
		&i.Timezone,
		&i.Enabled,
		&i.Input,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT id, workflow_id, workflow_version, cron_expression, timezone, enabled, input, last_run_at, next_run_at, created_at, updated_at FROM workflow_schedules
WHERE enabled = TRUE
  AND next_run_at <= ?
ORDER BY next_run_at ASC
`

func (q *Queries) ListDueSchedules(ctx context.Context, nextRunAt sql.NullTime) ([]WorkflowSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listDueSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowSchedule
	for rows.Next() {
		var i WorkflowSchedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.CronExpression,
			&i.Timezone,
			&i.Enabled,
			&i.Input,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, workflow_id, workflow_version, cron_expression, timezone, enabled, input, last_run_at, next_run_at, created_at, updated_at FROM workflow_schedules
WHERE enabled = TRUE
ORDER BY next_run_at ASC
`

func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]WorkflowSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowSchedule
	for rows.Next() {
		var i WorkflowSchedule
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.CronExpression,
			&i.Timezone,
			&i.Enabled,
			&i.Input,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleEnabled = `-- name: UpdateScheduleEnabled :exec
UPDATE workflow_schedules
SET enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE workflow_id = ? AND workflow_version = ?
`

type UpdateScheduleEnabledParams struct {
	Enabled         bool   `json:"enabled"`
	WorkflowID      string `json:"workflow_id"`
	WorkflowVersion int64  `json:"workflow_version"`
}

func (q *Queries) UpdateScheduleEnabled(ctx context.Context, arg UpdateScheduleEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleEnabled, arg.Enabled, arg.WorkflowID, arg.WorkflowVersion)
	return err
}

const updateScheduleLastRun = `-- name: UpdateScheduleLastRun :exec
UPDATE workflow_schedules
SET last_run_at = ?,
    next_run_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScheduleLastRunParams struct {
	LastRunAt sql.NullTime `json:"last_run_at"`
	NextRunAt sql.NullTime `json:"next_run_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) UpdateScheduleLastRun(ctx context.Context, arg UpdateScheduleLastRunParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleLastRun, arg.LastRunAt, arg.NextRunAt, arg.ID)
	return err
}

const updateWorkflowSchedule = `-- name: UpdateWorkflowSchedule :exec
UPDATE workflow_schedules
SET cron_expression = ?,
    timezone = ?,
    enabled = ?,
    input = ?,
    next_run_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE workflow_id = ? AND workflow_version = ?
`

type UpdateWorkflowScheduleParams struct {
	CronExpression  string         `json:"cron_expression"`
	Timezone        string         `json:"timezone"`
	Enabled         bool           `json:"enabled"`
	Input           sql.NullString `json:"input"`
	NextRunAt       sql.NullTime   `json:"next_run_at"`
	WorkflowID      string         `json:"workflow_id"`
	WorkflowVersion int64          `json:"workflow_version"`
}

func (q *Queries) UpdateWorkflowSchedule(ctx context.Context, arg UpdateWorkflowScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowSchedule,
		arg.CronExpression,
		arg.Timezone,
		arg.Enabled,
		arg.Input,
		arg.NextRunAt,
		arg.WorkflowID,
		arg.WorkflowVersion,
	)
	return err
}
