// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_run_steps.sql

package queries

import (
	"context"
	"database/sql"
)

const insertWorkflowRunStep = `-- name: InsertWorkflowRunStep :one
INSERT INTO workflow_run_steps (
    run_id,
    step_id,
    attempt,
    status,
    input,
    output,
    error,
    metadata,
    started_at,
    completed_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    COALESCE(?9, CURRENT_TIMESTAMP),
    ?10
)
RETURNING id, run_id, step_id, attempt, status, input, output, error, metadata, started_at, completed_at
`

type InsertWorkflowRunStepParams struct {
	RunID       string         `json:"run_id"`
	StepID      string         `json:"step_id"`
	Attempt     int64          `json:"attempt"`
	Status      string         `json:"status"`
	Input       sql.NullString `json:"input"`
	Output      sql.NullString `json:"output"`
	Error       sql.NullString `json:"error"`
	Metadata    sql.NullString `json:"metadata"`
	StartedAt   interface{}    `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) InsertWorkflowRunStep(ctx context.Context, arg InsertWorkflowRunStepParams) (WorkflowRunStep, error) {
	row := q.db.QueryRowContext(ctx, insertWorkflowRunStep,
		arg.RunID,
		arg.StepID,
		arg.Attempt,
		arg.Status,
		arg.Input,
		arg.Output,
		arg.Error,
		arg.Metadata,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i WorkflowRunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepID,
		&i.Attempt,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listWorkflowRunSteps = `-- name: ListWorkflowRunSteps :many
SELECT id, run_id, step_id, attempt, status, input, output, error, metadata, started_at, completed_at
FROM workflow_run_steps
WHERE run_id = ?1
ORDER BY started_at ASC, attempt ASC
`

func (q *Queries) ListWorkflowRunSteps(ctx context.Context, runID string) ([]WorkflowRunStep, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRunStep
	for rows.Next() {
		var i WorkflowRunStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepID,
			&i.Attempt,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.Error,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRunStep = `-- name: UpdateWorkflowRunStep :exec
UPDATE workflow_run_steps
SET status = ?1,
    output = COALESCE(?2, output),
    error = ?3,
    metadata = COALESCE(?4, metadata),
    completed_at = COALESCE(?5, completed_at)
WHERE run_id = ?6 AND step_id = ?7 AND attempt = ?8
`

type UpdateWorkflowRunStepParams struct {
	Status      string         `json:"status"`
	Output      sql.NullString `json:"output"`
	Error       sql.NullString `json:"error"`
	Metadata    sql.NullString `json:"metadata"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	RunID       string         `json:"run_id"`
	StepID      string         `json:"step_id"`
	Attempt     int64          `json:"attempt"`
}

func (q *Queries) UpdateWorkflowRunStep(ctx context.Context, arg UpdateWorkflowRunStepParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowRunStep,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.Metadata,
		arg.CompletedAt,
		arg.RunID,
		arg.StepID,
		arg.Attempt,
	)
	return err
}
