# Station CI Server Configuration
admin_username: ci-admin
ai_model: gpt-4o
ai_provider: openai
api_port: 8585
database_url: /app/data/station.db
debug: true
encryption_key: "{{ .ENCRYPTION_KEY }}"
local_mode: false  # Multi-user mode for CI server

# MCP settings for server mode
mcp:
  sync:
    confirm: false
    dry_run: false
    environment: "ci-server"
    interactive: false
    validate: true
    verbose: true

mcp_port: 3000
ssh_host_key_path: /app/ssh_host_key
ssh_port: 2222
telemetry_enabled: true