services:
  station-ci-server:
    image: station-base:latest
    container_name: station-ci-server
    
    volumes:
      - ./config.yml:/root/.config/station/config.yaml:ro
      - ./variables.yml:/app/environment/variables.yml:ro  
      - ./agents:/app/environment/agents:ro
      - ci-workspaces:/app/workspaces
      - ci-reports:/app/reports
      - ci-cache:/app/cache
      - ci-data:/app/data
      
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENCRYPTION_KEY=${STATION_ENCRYPTION_KEY}
      - STATION_ENV=ci-server
      
    ports:
      - "8585:8585"  # API Server
      - "3000:3000"  # MCP Server
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8585/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: always
    
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

volumes:
  ci-workspaces:
  ci-reports:
  ci-cache:
  ci-data: