apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: station-pipeline
spec:
  description: Run Station agents for code analysis
  workspaces:
  - name: source
    description: Workspace for source code
  params:
  - name: repo-url
    type: string
    description: Git repository URL

  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.repo-url)

  - name: code-review
    runAfter: [git-clone]
    taskRef:
      name: station-agent
    workspaces:
    - name: source
      workspace: source
    params:
    - name: agent
      value: "Code Reviewer"
    - name: task
      value: "Review code for bugs and best practices"

  - name: security-scan
    runAfter: [git-clone]
    taskRef:
      name: station-agent
    workspaces:
    - name: source
      workspace: source
    params:
    - name: agent
      value: "Security Analyst"
    - name: task
      value: "Scan for security vulnerabilities"
