apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: station-security-scan
  namespace: security
spec:
  description: Run Station security agents for vulnerability scanning
  params:
  - name: agent
    type: string
    description: Station agent to run (e.g., "Infrastructure Security Auditor")
  - name: task
    type: string
    description: Task description for the agent
  workspaces:
  - name: source
    description: Workspace containing source code to scan
  steps:
  - name: security-scan
    image: ghcr.io/cloudshipai/station-security:latest
    workingDir: $(workspaces.source.path)
    script: |
      #!/bin/sh
      set -e
      echo "═══════════════════════════════════════"
      echo "Station Security Agent: $(params.agent)"
      echo "═══════════════════════════════════════"
      stn agent run "$(params.agent)" "$(params.task)"
    env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: station-secrets
          key: openai-api-key
    - name: PROJECT_ROOT
      value: $(workspaces.source.path)
