apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: station-agent
spec:
  description: Run a Station agent
  params:
  - name: agent
    type: string
    description: Agent name to run
  - name: task
    type: string
    description: Task description for the agent
  workspaces:
  - name: source
    description: Workspace containing source code
  steps:
  - name: run-agent
    image: ghcr.io/cloudshipai/station:latest
    workingDir: $(workspaces.source.path)
    script: |
      #!/bin/sh
      set -e
      echo "Running agent: $(params.agent)"
      stn agent run "$(params.agent)" "$(params.task)"
    env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: station-secrets
          key: openai-api-key
