apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: station-pipeline-
spec:
  entrypoint: analysis-pipeline
  arguments:
    parameters:
    - name: repo-url
      value: https://github.com/your-org/your-repo.git

  volumeClaimTemplates:
  - metadata:
      name: workspace
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: analysis-pipeline
    steps:
    - - name: checkout
        template: git-checkout
    - - name: code-review
        template: run-agent
        arguments:
          parameters:
          - name: agent
            value: "Code Reviewer"
          - name: task
            value: "Review code for bugs and best practices"
      - name: security-scan
        template: run-agent
        arguments:
          parameters:
          - name: agent
            value: "Security Analyst"
          - name: task
            value: "Scan for security vulnerabilities"

  - name: git-checkout
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - git clone {{workflow.parameters.repo-url}} /workspace
      volumeMounts:
      - name: workspace
        mountPath: /workspace

  - name: run-agent
    inputs:
      parameters:
      - name: agent
      - name: task
    container:
      image: ghcr.io/cloudshipai/station:latest
      command: [stn]
      args:
        - agent
        - run
        - "{{inputs.parameters.agent}}"
        - "{{inputs.parameters.task}}"
      env:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: station-secrets
            key: openai-api-key
      volumeMounts:
      - name: workspace
        mountPath: /workspace
