dbs:
  - path: /data/station.db
    replicas:
      - type: s3
        bucket: ${LITESTREAM_S3_BUCKET}
        path: station-db
        region: ${LITESTREAM_S3_REGION:-us-east-1}
        access-key-id: ${LITESTREAM_S3_ACCESS_KEY_ID}
        secret-access-key: ${LITESTREAM_S3_SECRET_ACCESS_KEY}
        sync-interval: 10s
        retention: 24h
        
      # Alternative: Azure Blob Storage
      # - type: abs
      #   bucket: ${LITESTREAM_ABS_BUCKET}
      #   path: station-db
      #   account-name: ${LITESTREAM_ABS_ACCOUNT_NAME}
      #   account-key: ${LITESTREAM_ABS_ACCOUNT_KEY}
      
      # Alternative: Google Cloud Storage  
      # - type: gcs
      #   bucket: ${LITESTREAM_GCS_BUCKET}
      #   path: station-db
      #   service-account-json-path: /secrets/gcs-service-account.json

# Optional: Local file system backup (for development)
  - path: /data/station.db
    replicas:
      - type: file
        path: /backup/station-db-backup
        sync-interval: 30s
        retention: 168h  # 7 days