name: 'Setup Station CLI'
description: 'Install and configure Station CLI for GitHub Actions workflows'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  version:
    description: 'Station version to install (e.g., v0.22.0, latest)'
    required: false
    default: 'latest'

  provider:
    description: 'AI provider: openai, anthropic, gemini, or ollama'
    required: false
    default: 'openai'

  model:
    description: 'AI model to use (e.g., gpt-4o-mini, claude-3-5-sonnet-20241022)'
    required: false

  base-url:
    description: 'Custom API base URL (for Azure OpenAI, Ollama, etc.)'
    required: false

  workspace-path:
    description: 'Path to Station workspace/config directory'
    required: false
    default: '.'

  skip-init:
    description: 'Skip Station initialization (just install CLI)'
    required: false
    default: 'false'

outputs:
  version:
    description: 'Installed Station version'
    value: ${{ steps.install.outputs.version }}

  cli-path:
    description: 'Path to Station CLI binary'
    value: ${{ steps.install.outputs.cli-path }}

runs:
  using: 'composite'
  steps:
    - name: Install Station CLI
      id: install
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"

        if [ "$VERSION" = "latest" ]; then
          echo "📦 Fetching latest Station version..."
          VERSION=$(curl -sS https://api.github.com/repos/cloudshipai/station/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
        fi

        echo "📦 Installing Station CLI ${VERSION}..."

        # Detect OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        case "$ARCH" in
          x86_64) ARCH="amd64" ;;
          aarch64|arm64) ARCH="arm64" ;;
          armv7l) ARCH="arm" ;;
        esac

        # Download and install
        VERSION_NO_V="${VERSION#v}"
        DOWNLOAD_URL="https://github.com/cloudshipai/station/releases/download/${VERSION}/station_${VERSION_NO_V}_${OS}_${ARCH}.tar.gz"

        echo "Downloading from: $DOWNLOAD_URL"
        curl -fsSL "$DOWNLOAD_URL" -o /tmp/station.tar.gz
        tar -xzf /tmp/station.tar.gz -C /tmp
        chmod +x /tmp/stn
        sudo mv /tmp/stn /usr/local/bin/stn
        rm /tmp/station.tar.gz

        echo "✅ Station CLI ${VERSION} installed"

        # Set outputs
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "cli-path=/usr/local/bin/stn" >> $GITHUB_OUTPUT

    - name: Verify Installation
      shell: bash
      run: stn --version

    - name: Initialize Station
      if: inputs.skip-init != 'true'
      shell: bash
      env:
        STN_AI_PROVIDER: ${{ inputs.provider }}
        STN_AI_MODEL: ${{ inputs.model }}
        STN_AI_BASE_URL: ${{ inputs.base-url }}
      run: |
        cd "${{ inputs.workspace-path }}"

        echo "🔧 Initializing Station..."
        stn init --config ./config.yaml --yes 2>/dev/null || true

        echo "✅ Station initialized"
        echo "   Provider: ${STN_AI_PROVIDER:-openai}"
        [ -n "$STN_AI_MODEL" ] && echo "   Model: $STN_AI_MODEL"
        echo "   Workspace: ${{ inputs.workspace-path }}"
